### PR TITLE
Update 219.md

### PR DESCRIPTION
**Pull request by luigi29371**
Added our updated website, also added a list of awards for history purposes

### CODE REVIEW

**Comment by virtuald** [comment]
Everything you edited is metadata, so it won't actually show up as the page contents. If you wish to list non-metadata content, then replace the portion that says "no content has been added for this team". Your changes will actually break your page. :)

**Comment by virtuald** [comment]
... and yes, I need to make a schema checker for the metadata. Soon.

**Comment by luigi29371** [comment]
@virtuald Sorry, I'm a bit new here. Is it possible you could show how that could be implemented? I tried working with the FRC Wiki Style Guide but I wasn't particularly helped by it. I have enabled edits from maintainers.

**Comment by virtuald** [comment]
@MrMongru no worries... the documentation is still lacking. Check out this page for an example of one with more than just metadata: https://raw.githubusercontent.com/firstwiki/frc0000/gh-pages/_frc/200/254.md

The basic idea is that anything above the `---` has to be of a particular format, and it's rendered into that nice little table on the [page](https://firstwiki.github.io/frc0000/219) (and used for other things too). So capitalizing all of the items would be bad, as it wouldn't fit the format.

Anything below the `---` can be text written using Markdown format. That is where custom information about the team would go.

**Comment by virtuald** [comment]
Sorry for the delay in getting to this, but I've merged your updates now -- and a metadata validator has been enabled, so it'll flag stuff in the future.

**Pull request merged**
